# Generated by Django 2.2 on 2020-01-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='user_model',
            new_name='user_profile',
        ),
    ]
